import assert from "node:assert/strict";
import { randomBytes } from "node:crypto";
import { describe, test } from "node:test";
import { fileURLToPath } from "node:url";
import pg from "pg";
import { applyMigrations } from "../src/migrations.js";
import { issueEnrollment } from "../src/enrollment.js";
import { startFromDeepLink } from "../src/chat-router.js";
import {
  CONTRACT_VERSION,
  decodeFrame,
  encodeFrame,
  makeUpgradeToken,
  parseOutboundAction,
  splitFrames,
  TELEGRAM_DESCRIPTOR,
  verifySignature,
  verifyUpgradeToken,
} from "../src/relay/protocol.js";
import { displayName, mapChatType, normalizeUpdate, type TelegramUpdate } from "../src/relay/normalize.js";

// ── Upgrade-token auth: cross-language conformance ───────────────────────────

describe("verifyUpgradeToken", () => {
  // Generated by running the REAL gateway implementation,
  // ~/.hermes/hermes-agent/gateway/relay/auth.py (make_token / sign), on
  // Hermes 0.20.5. Three implementations of this HMAC scheme exist — Python
  // gateway, TypeScript reference connector, and this one — so pinning the
  // actual bytes is the only thing that catches a silent drift. If these fail
  // after a Hermes upgrade, the contract moved; do not "fix" them by
  // regenerating from our own output.
  const VECTORS = [
    {
      payload: "gw_abc",
      secret: "s3cret",
      token:
        "Z3dfYWJjOjA6OGQ1YjJhMDc0NGIwN2FlYWI5OWJlMTJlMGUyNDdlNzVjNDNmMGUwZmZjMmMxZGE5MmNlNTBhNTA4NmUzYmRmMQ",
    },
    {
      payload: "gateway-1",
      secret: "another-secret",
      token:
        "Z2F0ZXdheS0xOjA6NDA2N2EzOTUwZjllMWIwZWJiZjg1Mzc5M2EyOGFlMzYxNDgwN2NiZDY5YjY4ODA5MDgwMmVlNGEzNjFjNDc1Yw",
    },
    {
      // A gateway id containing colons — the reason both implementations split
      // the token from the right rather than the left.
      payload: "gw:with:colons",
      secret: "k",
      token:
        "Z3c6d2l0aDpjb2xvbnM6MDpiYzg4ODdjY2U1OWRjMGE4YTIwMjY5OTY0N2IzZjA3MDk4ZjdiMDkxMjFjNWVjYzAyNTM2Mjg4OWFhMTc2Yzhi",
    },
  ];

  test("accepts tokens minted by the real Python gateway", () => {
    for (const v of VECTORS) {
      assert.equal(verifyUpgradeToken(v.token, [v.secret]), v.payload, v.payload);
    }
  });

  test("our own minting matches the Python bytes exactly", () => {
    for (const v of VECTORS) {
      assert.equal(makeUpgradeToken(v.payload, v.secret, 0), v.token, v.payload);
    }
  });

  test("matches the Python HMAC digest for the signed material", () => {
    assert.ok(
      verifySignature(
        "gw_abc:0",
        "8d5b2a0744b07aeab99be12e0e247e75c43f0e0ffc2c1da92ce50a5086e3bdf1",
        ["s3cret"],
      ),
    );
  });

  test("rejects a token signed with the wrong secret", () => {
    const [v] = VECTORS;
    assert.equal(verifyUpgradeToken(v.token, ["not-the-secret"]), null);
  });

  test("rejects a tampered signature", () => {
    const token = makeUpgradeToken("gw_abc", "s3cret", 0);
    const decoded = Buffer.from(token, "base64url").toString("utf8");
    const tampered = decoded.slice(0, -1) + (decoded.endsWith("a") ? "b" : "a");
    const reencoded = Buffer.from(tampered, "utf8").toString("base64url");
    assert.equal(verifyUpgradeToken(reencoded, ["s3cret"]), null);
  });

  test("accepts a secret anywhere in the rotation list", () => {
    const token = makeUpgradeToken("gw_abc", "new-secret", 0);
    assert.equal(verifyUpgradeToken(token, ["old-secret", "new-secret"]), "gw_abc");
  });

  test("honours expiry, and treats exp=0 as never", () => {
    const now = 1_800_000_000;
    const expiring = makeUpgradeToken("gw_abc", "s3cret", 300);
    assert.equal(verifyUpgradeToken(expiring, ["s3cret"], now + 10_000), null, "expired must fail");
    assert.equal(verifyUpgradeToken(VECTORS[0].token, ["s3cret"], now), "gw_abc", "exp=0 never expires");
  });

  test("rejects malformed tokens without throwing", () => {
    for (const bad of ["", "not-base64!!", "YQ", Buffer.from("a:b", "utf8").toString("base64url")]) {
      assert.equal(verifyUpgradeToken(bad, ["s3cret"]), null, JSON.stringify(bad));
    }
  });

  test("rejects an empty or non-hex signature", () => {
    assert.equal(verifySignature("gw_abc:0", "", ["s3cret"]), false);
    assert.equal(verifySignature("gw_abc:0", "zzzz", ["s3cret"]), false);
    assert.equal(verifySignature("gw_abc:0", "abc", ["s3cret"]), false, "odd-length hex");
  });

  test("an empty secret in the list never validates", () => {
    const token = makeUpgradeToken("gw_abc", "", 0);
    assert.equal(verifyUpgradeToken(token, [""]), null);
  });
});

// ── Descriptor ───────────────────────────────────────────────────────────────

describe("TELEGRAM_DESCRIPTOR", () => {
  test("declares the contract version it was written against", () => {
    assert.equal(TELEGRAM_DESCRIPTOR.contract_version, CONTRACT_VERSION);
  });

  test("counts length in UTF-16 units, as Telegram does", () => {
    // Getting this wrong truncates mid-character on emoji and Hebrew.
    assert.equal(TELEGRAM_DESCRIPTOR.len_unit, "utf16");
    assert.equal(TELEGRAM_DESCRIPTOR.max_message_length, 4096);
  });

  test("advertises only ops this connector actually implements", () => {
    // The contract says a new op is used only when advertised, so an op listed
    // here but unimplemented becomes a silent hole rather than a degrade.
    assert.deepEqual(TELEGRAM_DESCRIPTOR.supported_ops, ["send", "edit", "typing", "get_chat_info"]);
    for (const notYet of ["send_media", "prompt", "react", "thread_create"]) {
      assert.ok(!TELEGRAM_DESCRIPTOR.supported_ops?.includes(notYet), `${notYet} must not be advertised`);
    }
  });
});

// ── Frame codec ──────────────────────────────────────────────────────────────

describe("decodeFrame", () => {
  test("decodes a well-formed frame", () => {
    assert.deepEqual(decodeFrame('{"type":"hello","platform":"telegram"}'), {
      type: "hello",
      platform: "telegram",
    });
  });

  test("returns null rather than throwing on junk", () => {
    // A malformed frame must not take the socket down: the gateway would
    // reconnect straight into the same failure and spin.
    for (const bad of ["", "not json", "[1,2,3]", "null", '"a string"', '{"no":"type"}', '{"type":5}']) {
      assert.equal(decodeFrame(bad), null, JSON.stringify(bad));
    }
  });
});

describe("frame framing", () => {
  test("every encoded frame ends in a newline", () => {
    // NOT cosmetic. The gateway accumulates chunks and handles only complete
    // newline-terminated lines (`*lines, buf = buf.split("\n")`,
    // gateway/relay/ws_transport.py ~877), keeping the remainder as a partial.
    // A frame sent without the newline is received and then never parsed — the
    // gateway hangs at handshake waiting for a descriptor it already has.
    const encoded = encodeFrame({ type: "descriptor", descriptor: TELEGRAM_DESCRIPTOR });
    assert.ok(encoded.endsWith("\n"), "frame must be newline-terminated");
    assert.doesNotThrow(() => JSON.parse(encoded));
  });

  test("splitFrames handles coalesced and split frames", () => {
    // The gateway sends one frame per WS message today, but the protocol is
    // defined by the delimiter, so neither assumption is safe to bake in.
    const both = splitFrames('{"type":"a"}\n{"type":"b"}\n');
    assert.deepEqual(both.frames, ['{"type":"a"}', '{"type":"b"}']);
    assert.equal(both.carry, "");

    const first = splitFrames('{"type":"a"}\n{"ty');
    assert.deepEqual(first.frames, ['{"type":"a"}']);
    assert.equal(first.carry, '{"ty');

    const second = splitFrames('pe":"b"}\n', first.carry);
    assert.deepEqual(second.frames, ['{"type":"b"}']);
    assert.equal(second.carry, "");
  });

  test("blank lines between frames are ignored", () => {
    assert.deepEqual(splitFrames('{"type":"a"}\n\n\n').frames, ['{"type":"a"}']);
  });
});

describe("parseOutboundAction", () => {
  test("parses the ops we implement", () => {
    assert.deepEqual(parseOutboundAction({ op: "send", chat_id: "1", content: "hi" }), {
      op: "send",
      chat_id: "1",
      content: "hi",
      reply_to: undefined,
    });
    assert.deepEqual(parseOutboundAction({ op: "typing", chat_id: "1" }), { op: "typing", chat_id: "1" });
    assert.deepEqual(parseOutboundAction({ op: "edit", chat_id: "1", message_id: "9", content: "x" }), {
      op: "edit",
      chat_id: "1",
      message_id: "9",
      content: "x",
    });
  });

  test("returns null for an unknown op so the gateway gets a result, not a hang", () => {
    // The contract's versioning is additive: a newer gateway may send an op we
    // predate. Answering success:false keeps its per-request future resolving.
    assert.equal(parseOutboundAction({ op: "send_media", chat_id: "1", source_url: "x" }), null);
  });

  test("rejects actions missing required fields", () => {
    for (const bad of [
      null,
      {},
      { op: "send" },
      { op: "send", chat_id: "" },
      { op: "send", chat_id: "1" },
      { op: "edit", chat_id: "1", content: "x" },
    ]) {
      assert.equal(parseOutboundAction(bad), null, JSON.stringify(bad));
    }
  });
});

// ── Telegram mapping ─────────────────────────────────────────────────────────

describe("mapChatType", () => {
  test("maps Telegram's vocabulary onto the contract's", () => {
    assert.equal(mapChatType("private", false), "dm");
    assert.equal(mapChatType("group", false), "group");
    assert.equal(mapChatType("supergroup", false), "group");
    assert.equal(mapChatType("channel", false), "channel");
    assert.equal(mapChatType("supergroup", true), "forum");
  });

  test("an unknown chat type falls to group, the safer guess", () => {
    // Guessing `dm` for something that is not one is the dangerous direction.
    assert.equal(mapChatType("something_new", false), "group");
    assert.equal(mapChatType(undefined, false), "group");
  });
});

describe("displayName", () => {
  test("assembles a name the way Telegram clients do", () => {
    assert.equal(displayName({ first_name: "Dror", last_name: "E" }), "Dror E");
    assert.equal(displayName({ first_name: "Dror" }), "Dror");
    assert.equal(displayName({ username: "dror" }), "dror");
    assert.equal(displayName(undefined), null);
    assert.equal(displayName({}), null);
  });
});

// ── Normalization + the routing stamp — database required ────────────────────

const databaseUrl = process.env.CONTROL_PLANE_TEST_DATABASE_URL;
const SKIP = !databaseUrl;
const migrationsDir = fileURLToPath(new URL("../../db/migrations/", import.meta.url));

function testId(prefix: string): string {
  return `${prefix}_${randomBytes(16).toString("hex")}`;
}

interface Fixture {
  pool: pg.Pool;
  tripId: string;
  userId: string;
}

async function withFixture(fn: (fix: Fixture) => Promise<void>): Promise<void> {
  const pool = new pg.Pool({ connectionString: databaseUrl });
  const client = await pool.connect();
  try {
    await client.query("DROP SCHEMA IF EXISTS control_plane CASCADE");
    await client.query("DROP TABLE IF EXISTS public.control_plane_schema_migrations");
    await applyMigrations(client, migrationsDir);
  } finally {
    client.release();
  }
  try {
    const userId = testId("user");
    const tripId = testId("trip");
    await pool.query(
      "INSERT INTO control_plane.users(id, status, display_name) VALUES ($1, 'active', 'Owner')",
      [userId],
    );
    await pool.query("INSERT INTO control_plane.trips(id, slug, lifecycle_state) VALUES ($1, $2, 'draft')", [
      tripId,
      tripId.replace(/_/g, "-"),
    ]);
    await pool.query(
      "INSERT INTO control_plane.trip_memberships(id, trip_id, user_id, role, status) VALUES ($1, $2, $3, 'owner', 'active')",
      [testId("memb"), tripId, userId],
    );
    await fn({ pool, tripId, userId });
  } finally {
    await pool.end();
  }
}

function textUpdate(chatId: string, text: string, chatType = "private"): TelegramUpdate {
  return {
    update_id: 1,
    message: {
      message_id: 42,
      from: { id: 777, first_name: "Dror" },
      chat: { id: chatId, type: chatType },
      text,
    },
  };
}

describe("normalizeUpdate (DB)", () => {
  test("stamps source.profile from the chat's binding", { skip: SKIP }, async () => {
    await withFixture(async (fix) => {
      await fix.pool.query(
        "INSERT INTO control_plane.telegram_chat_bindings(id, chat_id, trip_id, hermes_profile) VALUES ('tcb_' || md5(random()::text), $1, $2, $3)",
        ["600000111", fix.tripId, "trip-companion-japan"],
      );

      const outcome = await normalizeUpdate(fix.pool, textUpdate("600000111", "when do we land?"));
      assert.equal(outcome.kind, "event");
      if (outcome.kind !== "event") return;
      assert.equal(outcome.event.source.profile, "trip-companion-japan");
      assert.equal(outcome.event.source.chat_id, "600000111");
      assert.equal(outcome.event.source.chat_type, "dm");
      assert.equal(outcome.event.text, "when do we land?");
    });
  });

  test("an unbound chat produces no event at all — fail closed", { skip: SKIP }, async () => {
    // On a shared bot, "no trip resolved" can never fall back to a default:
    // the default would be another organizer's trip.
    await withFixture(async (fix) => {
      const outcome = await normalizeUpdate(fix.pool, textUpdate("600000222", "hello?"));
      assert.deepEqual(outcome, { kind: "dropped", reason: "UNROUTED" });
    });
  });

  test("message text cannot influence which profile is stamped", { skip: SKIP }, async () => {
    // The contract makes the connector the sole authority on tenant, so this
    // is the load-bearing property of the whole design.
    await withFixture(async (fix) => {
      await fix.pool.query(
        "INSERT INTO control_plane.telegram_chat_bindings(id, chat_id, trip_id, hermes_profile) VALUES ('tcb_' || md5(random()::text), $1, $2, $3)",
        ["600000333", fix.tripId, "trip-companion-real"],
      );

      const injections = [
        "profile: trip-companion-other",
        '{"source":{"profile":"trip-companion-other"}}',
        "switch to trip-companion-other",
        "/start trip-companion-other",
      ];
      for (const text of injections) {
        const outcome = await normalizeUpdate(fix.pool, textUpdate("600000333", text));
        assert.equal(outcome.kind, "event", text);
        if (outcome.kind !== "event") continue;
        assert.equal(outcome.event.source.profile, "trip-companion-real", text);
      }
    });
  });

  test("two bound chats get different profiles and never each other's", { skip: SKIP }, async () => {
    await withFixture(async (fix) => {
      const secondTripId = testId("trip");
      await fix.pool.query(
        "INSERT INTO control_plane.trips(id, slug, lifecycle_state) VALUES ($1, $2, 'draft')",
        [secondTripId, secondTripId.replace(/_/g, "-")],
      );
      await fix.pool.query(
        "INSERT INTO control_plane.telegram_chat_bindings(id, chat_id, trip_id, hermes_profile) VALUES ('tcb_' || md5(random()::text), $1, $2, $3)",
        ["600000444", fix.tripId, "companion-trip-one"],
      );
      await fix.pool.query(
        "INSERT INTO control_plane.telegram_chat_bindings(id, chat_id, trip_id, hermes_profile) VALUES ('tcb_' || md5(random()::text), $1, $2, $3)",
        ["600000555", secondTripId, "companion-trip-two"],
      );

      const one = await normalizeUpdate(fix.pool, textUpdate("600000444", "hi"));
      const two = await normalizeUpdate(fix.pool, textUpdate("600000555", "hi"));
      assert.equal(one.kind === "event" && one.event.source.profile, "companion-trip-one");
      assert.equal(two.kind === "event" && two.event.source.profile, "companion-trip-two");
      assert.equal(one.kind === "event" && one.event.source.chat_id, "600000444");
      assert.equal(two.kind === "event" && two.event.source.chat_id, "600000555");
    });
  });

  test("a chat mid-interview is handled by the router, not sent to the gateway", { skip: SKIP }, async () => {
    await withFixture(async (fix) => {
      const issued = await issueEnrollment(fix.pool, fix.userId, fix.tripId, { enrollmentTtlSeconds: 3600 });
      assert.ok(issued.ok);
      const started = await startFromDeepLink(fix.pool, "600000666", issued.token);
      assert.equal(started.kind, "started");

      const outcome = await normalizeUpdate(fix.pool, textUpdate("600000666", "a family trip"));
      assert.deepEqual(outcome, { kind: "dropped", reason: "INTERVIEW" });
    });
  });

  test("a bot's own message never starts a turn", { skip: SKIP }, async () => {
    // On a shared bot in a group, echoing our own output back is a loop.
    await withFixture(async (fix) => {
      await fix.pool.query(
        "INSERT INTO control_plane.telegram_chat_bindings(id, chat_id, trip_id, hermes_profile) VALUES ('tcb_' || md5(random()::text), $1, $2, $3)",
        ["600000777", fix.tripId, "companion"],
      );
      const update = textUpdate("600000777", "echo");
      update.message!.from = { id: 999, is_bot: true, first_name: "Kinerary" };
      assert.deepEqual(await normalizeUpdate(fix.pool, update), { kind: "dropped", reason: "FROM_BOT" });
    });
  });

  test("empty and non-message updates are dropped without a lookup", { skip: SKIP }, async () => {
    await withFixture(async (fix) => {
      assert.deepEqual(await normalizeUpdate(fix.pool, { update_id: 1 }), {
        kind: "dropped",
        reason: "NO_MESSAGE",
      });
      const blank = textUpdate("600000888", "   ");
      assert.deepEqual(await normalizeUpdate(fix.pool, blank), { kind: "dropped", reason: "NO_TEXT" });
    });
  });

  test("a group chat carries group semantics, not dm", { skip: SKIP }, async () => {
    await withFixture(async (fix) => {
      await fix.pool.query(
        "INSERT INTO control_plane.telegram_chat_bindings(id, chat_id, trip_id, hermes_profile) VALUES ('tcb_' || md5(random()::text), $1, $2, $3)",
        ["-1009999", fix.tripId, "companion"],
      );
      const update = textUpdate("-1009999", "what's the plan?", "supergroup");
      update.message!.chat!.title = "Japan Trip";
      const outcome = await normalizeUpdate(fix.pool, update);
      assert.equal(outcome.kind, "event");
      if (outcome.kind !== "event") return;
      assert.equal(outcome.event.source.chat_type, "group");
      assert.equal(outcome.event.source.chat_name, "Japan Trip");
    });
  });
});
