#!/usr/bin/env bash
# scripts/hermes-pipeline/03-bootstrap-hermes-profile.sh
#
# Runs ON the Hermes host — invoked over SSH by run.sh, which exports these
# first: SITE_HOST_IP, PROVISION_PORT, MCP_PORT, PROVISION_API_KEY,
# MCP_API_KEY, HERMES_PROFILE_NAME, INTERVIEW_SRC_DIR (a temp dir run.sh
# scp'd INTERVIEW.md + answers.example.json into on this machine).
#
# Sets up a dedicated Hermes profile for the trip-creation interviewer:
#   - creates the profile if missing
#   - wires config.yaml's mcp_servers at provision.js + mcp.js on the site host
#   - writes SOUL.md with the interviewer's persona/hard-rules
#   - installs a proper Hermes skill wrapping INTERVIEW.md, loaded on demand
#     via skill_view instead of bloating the system prompt
#
# Deliberately stops short of: picking a model/provider (needs your own
# key), wiring a Telegram bot token, and starting the gateway — those need a
# live decision from you and are the manual steps printed at the end.

set -euo pipefail

: "${SITE_HOST_IP:?}"; : "${PROVISION_PORT:?}"; : "${MCP_PORT:?}"
: "${PROVISION_API_KEY:?}"; : "${MCP_API_KEY:?}"; : "${HERMES_PROFILE_NAME:?}"
: "${INTERVIEW_SRC_DIR:?}"

command -v hermes >/dev/null 2>&1 || {
  echo "[fail] 'hermes' CLI not found on this machine. Install it first:" >&2
  echo "  curl -fsSL https://hermes-agent.nousresearch.com/install.sh | bash" >&2
  exit 1
}
command -v ruby >/dev/null 2>&1 || {
  echo "[fail] ruby not found (used here only for a safe YAML merge — ships with macOS by default)." >&2
  exit 1
}

PROFILE_HOME="$HOME/.hermes/profiles/${HERMES_PROFILE_NAME}"

if [ -d "$PROFILE_HOME" ]; then
  echo "[info] Profile '${HERMES_PROFILE_NAME}' already exists at ${PROFILE_HOME}"
else
  echo "[info] Creating Hermes profile '${HERMES_PROFILE_NAME}'..."
  hermes profile create "$HERMES_PROFILE_NAME" \
    --description "Runs the Kinerary trip-creation interview over Telegram DM and provisions the site at the end."
fi
mkdir -p "$PROFILE_HOME"

# ── config.yaml: merge mcp_servers without touching model/provider/etc ──────
CONFIG_YAML="$PROFILE_HOME/config.yaml"
touch "$CONFIG_YAML"
CONFIG_YAML="$CONFIG_YAML" SITE_HOST_IP="$SITE_HOST_IP" PROVISION_PORT="$PROVISION_PORT" \
MCP_PORT="$MCP_PORT" PROVISION_API_KEY="$PROVISION_API_KEY" MCP_API_KEY="$MCP_API_KEY" \
ruby -ryaml <<'RUBY'
path = ENV.fetch('CONFIG_YAML')
config = (File.exist?(path) && !File.zero?(path)) ? (YAML.load_file(path) || {}) : {}
config['mcp_servers'] ||= {}
config['mcp_servers']['trip_provision'] = {
  'url'     => "http://#{ENV['SITE_HOST_IP']}:#{ENV['PROVISION_PORT']}/sse",
  'headers' => { 'X-API-Key' => ENV['PROVISION_API_KEY'] },
  # Deliberately read-only. create_trip / verify_trip / set_trip_logo /
  # get_activation_plan / activate_trip are excluded on purpose — this agent
  # conducts the interview and hands off a finished answers.json (see
  # SOUL.md), it does not itself write files or restart the live container.
  # A deterministic script (04-create-trip-from-answers.sh) does that part.
  'tools' => { 'include' => ['provision_health', 'list_trips', 'validate_answers'] },
}
config['mcp_servers']['trip_data'] = {
  'url'     => "http://#{ENV['SITE_HOST_IP']}:#{ENV['MCP_PORT']}/sse",
  'headers' => { 'X-API-Key' => ENV['MCP_API_KEY'] },
}
File.write(path, config.to_yaml)
RUBY
echo "[ ok ] config.yaml mcp_servers -> provision.js + mcp.js on ${SITE_HOST_IP}"

# ── SOUL.md — only if missing or still auto-generated (don't clobber hand-edits) ──
SOUL_MD="$PROFILE_HOME/SOUL.md"
MARKER="<!-- auto-generated by scripts/hermes-pipeline/03-bootstrap-hermes-profile.sh -->"
if [ ! -f "$SOUL_MD" ] || head -1 "$SOUL_MD" | command grep -qF "$MARKER"; then
  cat > "$SOUL_MD" <<EOF
$MARKER
# Trip Setup — interviewer persona

You run the trip-creation interview for the Kinerary trip-site framework, over
Telegram DM, with one person at a time.

WHO YOU ARE TALKING TO
The person messaging you is the trip organizer. Assume this unless they say
otherwise. They are not technical. They have not read any documentation and
should not have to. Never mention JSON, config files, slugs, MCP, containers,
or file paths — not once, not as an aside.

YOUR JOB
Have a real conversation that produces a working trip website. When this task
comes up, load the trip-creation-interview skill — it has the full question
script (what to ask, in what order, what to default, and what never to ask
about). Work through it in order. Do not invent sections it doesn't have.

Language: match whatever they write to you. If they open in Hebrew, the whole
interview is in Hebrew, including the onboarding pack at the end.

HOW TO ASK
- Small batches. Two or three related things per message, never a form.
- Never block on something they don't have yet. Write "TBD" and move on.
- If they give you something in passing that answers a later question, take
  it and don't ask again.
- Keep messages short. This is a phone.

TOOLS — WHEN, AND WHEN NOT
You only have READ-ONLY provisioning tools. You cannot create, verify, or
activate a trip yourself — that is intentional, not a bug to work around.
- provision_health: once, at the start, before you ask anything. If it
  fails, say the setup isn't reachable and stop.
- list_trips: before starting, to check the trip doesn't already exist.
- validate_answers: freely, throughout. It's read-only — use it liberally
  to catch a duplicate username or a family pointing at a non-participant
  while the person is still in front of you.

FINISHING
When the interview is complete, write the finished answers object as JSON to
this exact path on this machine: ${PROFILE_HOME}/workspace/answers.json
(create the workspace/ directory if it doesn't exist). That file is what
gets picked up next — writing it is the last thing you do, not calling a
tool to "finish the job". Tell the organizer their answers are saved and
that the site will be set up next, without giving a technical reason why.

NEVER:
- Claim you created or activated the trip. You didn't and can't — say it's
  saved and someone will finish setting it up.
- Use force/overwrite language about an existing trip — that's not yours to
  decide; say so if list_trips shows one already exists with this name.
- Put a password, a booking confirmation code, or a hotel PIN into a message.

THE SENSITIVE PART
The interview asks what the trip's companion bot should keep in mind about
these specific people. Those answers are private by default and stay
private. Do not offer to share any of it with the family. If they start
describing someone's medical condition, redirect — that belongs stored on
the person, not in a general instruction.

IF SOMETHING GOES WRONG
Say what happened in plain language, say what you're doing about it, and if
you can't fix it, say that instead of trying something clever.
EOF
  echo "[ ok ] SOUL.md written"
else
  echo "[info] SOUL.md exists and looks hand-edited (no auto-gen marker) — left alone"
fi

# ── Skill package: wraps INTERVIEW.md, loaded on demand via skill_view ──────
SKILL_DIR="$PROFILE_HOME/skills/kinerary/trip-creation-interview"
mkdir -p "$SKILL_DIR/references"
cp "$INTERVIEW_SRC_DIR/INTERVIEW.md" "$SKILL_DIR/references/INTERVIEW.md"
cp "$INTERVIEW_SRC_DIR/answers.example.json" "$SKILL_DIR/references/answers.example.json"

cat > "$SKILL_DIR/SKILL.md" <<EOF
---
name: trip-creation-interview
description: "Use when running the Kinerary trip-creation interview over Telegram DM with a prospective trip organizer."
version: 1.0.0
metadata:
  hermes:
    tags: [kinerary, trip-setup, interview]
---

# Trip-creation interview

Full question script: \`skill_view("trip-creation-interview", "references/INTERVIEW.md")\`.
Exact JSON shape to build up as you go: \`skill_view("trip-creation-interview", "references/answers.example.json")\`.

## Procedure

1. Call \`provision_health\` before asking anything. If it fails, tell the
   person the setup isn't reachable right now and stop.
2. Call \`list_trips\` to check a trip with this name doesn't already exist.
3. Load \`references/INTERVIEW.md\` and follow it in order — it tells you what
   to ask, what to default, and what to never ask about (see its §9.4 on
   sensitive per-person notes).
4. Maintain an \`answers\` object shaped like \`references/answers.example.json\`.
   After each major section, call \`validate_answers\` on what you have so far
   — it's read-only and catches mistakes while the person is still here.
5. When the interview is complete, write the finished \`answers\` object as
   JSON to \`${PROFILE_HOME}/workspace/answers.json\` (create the directory
   if needed). You do not have a tool to create or activate the trip
   yourself — see SOUL.md's FINISHING section. That is the end of your job
   for this conversation.
6. Finish with the onboarding-pack framing from INTERVIEW.md §11, but note
   that the site isn't live yet rather than promising specific timing.

## Pitfalls

- Never say "JSON", "config", or "slug" to the organizer — see SOUL.md.
- Don't imply you've created or activated anything — you write the answers
  file and stop; someone else finishes the setup.
- A duplicate username or a family pointing at a non-participant is exactly
  what \`validate_answers\` exists to catch — use it, don't skip it because
  the conversation is flowing well.
EOF
echo "[ ok ] Skill installed: ${SKILL_DIR}"

echo
echo "[ ok ] Phase 3 (Hermes profile) complete: ${HERMES_PROFILE_NAME}"
echo "[info] This agent can only READ from provision.js (provision_health, list_trips,"
echo "       validate_answers). It cannot create, verify, or activate a trip itself —"
echo "       it hands off a finished workspace/answers.json for 04-create-trip-from-answers.sh"
echo "       (run on the site host) to pick up deterministically."
echo "[warn] STILL MANUAL, on this machine, because they need a live decision from you:"
echo "  1. hermes -p ${HERMES_PROFILE_NAME} model      # pick a provider/model + API key"
echo "  2. hermes -p ${HERMES_PROFILE_NAME} gateway setup   # wire the Telegram bot token"
echo "  3. Verify the MCP connection actually works — ask the agent to call provision_health"
echo "     (our servers use the SSE MCP transport; Hermes's HTTP client SHOULD auto-negotiate"
echo "     it per its docs, but this is the one thing not confirmed by a live test yet)."
echo "  4. hermes -p ${HERMES_PROFILE_NAME} gateway start"
